import type { Metadata } from "next";
import { Cormorant_Infant, Urbanist } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/header";
import "../../app/globals.css";
import { SanityLive } from "@/sanity/lib/live";
import Footer from "@/components/footer";
import { ReactLenis } from "@/utils/lenis";



const cormorant_infant = Cormorant_Infant({
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  variable: "--font-cormorant",
  display: "swap",
});


const urbanist = Urbanist({
  subsets: ["latin"],
  variable: "--font-urbanist",
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider dynamic>
        <ReactLenis root>
          <body
            className={`${urbanist.variable} ${cormorant_infant.variable} antialiased`}
          >
            <Header />
            {children}
            <Footer />
            <SanityLive />
          </body>
        </ReactLenis>
      </ClerkProvider>
    </html>
  );
}
